### ISSUE TITLE
Save without popup window

### ISSUE THREAD

**Issue by KuenzelIT** [nunoarruda/auto-save-html#6]
Hi,

is it possible to let the exentsion save the .html file automatically without a window popping up for the download?

Thanks!

**Comment by nunoarruda** [comment]
I don't know if that's technically possible but I'll take a look when I have the time.

**Comment by KuenzelIT** [comment]
Thank you for the quick response!

**Comment by nunoarruda** [comment]
Hey @KuenzelIT can you check your Firefox Preferences/Options and see if under General -> Downloads you have the option "Always ask you where to save files" turned on?

**Comment by KuenzelIT** [comment]
Yes, it's turned on.

**Comment by nunoarruda** [comment]
@KuenzelIT that's it then, you need to use the "Save files to" option to skip the popup, which I believe is the default option. You must have manually set the "Always ask you where to save files" option or it is part of your settings synced via your Firefox Account.

**Comment by KuenzelIT** [comment]
Makes sense, thank you!
